<<<<<<< HEAD
[package]
name = "websocket-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
=======
[package]
name = "websocket-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
>>>>>>> 21d985d (first commit)
